# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kessler < Formula
  desc "🛰️ Intelligent CLI tool to find and safely clean build artifacts & caches"
  homepage "https://github.com/hariharen9/kessler"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.0/kessler_0.1.0_darwin_amd64.tar.gz"
      sha256 "de292321f2e1bbcd77cf30fd4eeb5a9381b61efd8c65421e5cb119e19cd1c5d7"

      define_method(:install) do
        bin.install "kessler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.0/kessler_0.1.0_darwin_arm64.tar.gz"
      sha256 "90aad4e5fa5da814a4b7ba5b974b102c55f671229e71326ae39152bf295c7192"

      define_method(:install) do
        bin.install "kessler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.0/kessler_0.1.0_linux_amd64.tar.gz"
      sha256 "c47d681ffbb48c4890c27526ace7cdb85a03e3abafaed33e4f7a974c2f308459"
      define_method(:install) do
        bin.install "kessler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.0/kessler_0.1.0_linux_arm64.tar.gz"
      sha256 "6236a0536a70521e21d96e755db2e371f52760b139ab8de96fa3742c7a70124d"
      define_method(:install) do
        bin.install "kessler"
      end
    end
  end

  test do
    system "#{bin}/kessler", "--help"
  end
end
