# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kessler < Formula
  desc "🛰️ Intelligent CLI tool to find and safely clean build artifacts & caches"
  homepage "https://github.com/hariharen9/kessler"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.1/kessler_0.1.1_darwin_amd64.tar.gz"
      sha256 "4478a8c9a2bcd502efaf5acaaa619e59770c8b887bc8e017b05e5b560eba6762"

      define_method(:install) do
        bin.install "kessler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.1/kessler_0.1.1_darwin_arm64.tar.gz"
      sha256 "51aaea859e090ca4d10477e041206287e7720af7f6209f0de3194a294b063e9d"

      define_method(:install) do
        bin.install "kessler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.1/kessler_0.1.1_linux_amd64.tar.gz"
      sha256 "4fa42b50f13415ed954baa46430230835e3008bb63f636f87cfdd4874a87a45d"
      define_method(:install) do
        bin.install "kessler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hariharen9/kessler/releases/download/v0.1.1/kessler_0.1.1_linux_arm64.tar.gz"
      sha256 "c8a7ee3c725697388d0d64b8ddbc875ff58f352d86664c00ae13523a71e423b1"
      define_method(:install) do
        bin.install "kessler"
      end
    end
  end

  test do
    system "#{bin}/kessler", "--help"
  end
end
